### ISSUE TITLE
Hangs forever on Windows machines with no config file to find

### ISSUE THREAD

**Issue by maslade** [grantila/ts-to-openapi#3]
I tried running this based on documentation and it was hanging permanently. I discovered the findFile() logic in util.ts assumes a Linux-like root paths. If I add the config file it's trying to detect it works okay, otherwise it spins forever checking the "C:\\" directory over and over.

**Comment by maslade** [comment]
Proposed fix: https://github.com/grantila/ts-to-openapi/pull/4

**Comment by grantila** [comment]
Good issue and PR, thanks!
