### ISSUE TITLE
Unable to convert some typescript files

### ISSUE THREAD

**Issue by trixprod** [grantila/ts-to-openapi#8]
Hello,
I'm trying to convert a provided typescript file containing some charting definitions to an openapi model definition.

I think this file (index.d.ts in the zip) is incorrect in some ways but the stack trace error  doesn't help in tracking the source of the issue.

> node_modules\ts-to-openapi\dist\bin\ts-to-openapi.js:132
>         throw error;
>         ^
> 
> Error: Reference type not set yet
>     at ReferenceType.getType (node_modules\ts-json-schema-generator\dist\src\Type\ReferenceType.js:34:19)
>     at Object.derefType (node_modules\ts-json-schema-generator\dist\src\Utils\derefType.js:13:31)
>     at TypeOperatorNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\NodeParser\TypeOperatorNodeParser.js:21:37)
>     at ChainNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\ChainNodeParser.js:29:54)
>     at MappedTypeNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\NodeParser\MappedTypeNodeParser.js:28:53)
>     at ChainNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\ChainNodeParser.js:29:54)
>     at TypeAliasNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\NodeParser\TypeAliasNodeParser.js:33:43)
>     at AnnotatedNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\NodeParser\AnnotatedNodeParser.js:19:47)
>     at ExposeNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\ExposeNodeParser.js:17:45)
>     at CircularReferenceNodeParser.createType (node_modules\ts-json-schema-generator\dist\src\CircularReferenceNodeParser.js:21:43)
> 

[index.d.zip](https://github.com/grantila/ts-to-openapi/files/5938607/index.d.zip)

Can you provide a way to better debug the generation process ?

Thank you.

**Comment by grantila** [comment]
This package uses `ts-json-schema-generator` which is probably what fails here (without a better stacktrace).
Your file contains `Partial<>` which I'm not sure will work (like any other generic), and e.g. the `PlotlyHTMLElement` contains function types, which might cause this (function types can't be converted to JSON schema).

I've left this package, and am working on `typeconv` which will replace this and convert freely between JSON Schema, GraphQL and TypeScript. And eventually OpenAPI (but not initially).

**Comment by grantila** [comment]
Try https://github.com/grantila/typeconv which might not crash. By default it ignores types it doesn't understand.

This package will be deprecated once typeconv does as good of a job with both TypeScript and Open API. Currently it's a little more limited in both.
